final_project/animal_adoption/animal_adoption/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', Login.as_view(), name = "login"),
    url(r'^adopt/', Adopt.as_view(), name = "adopt"),
    url(r'^register/', Register.as_view(), name = "register"),
    # url(r'^random_pet/', APISample.as_view(), name = "random_pet"),
    url(r'^find_pet/', FindPet.as_view(), name = "find_pet"),
    url(r'^find_shelter/', FindShelter.as_view(), name = "find_shelter"),
    url(r'^details/', Details.as_view(), name = "details"),
    url(r'^', APISample.as_view(), name = "home"),
]

final_project/animal_adoption/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('animal_adoption.urls', namespace = "animal_adoption")),
]

final_project/animal_adoption/animal_adoption/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	username = models.CharField(max_length=30, default = None)
	password = models.CharField(max_length=30, default = None)
	email = models.EmailField(default = None)
	# website = models.URLField(blank = True)

	def __unicode__(self):
		return self.user.username



# class User(AbstractBaseUser, PermissionsMixin):
#     USERNAME_FIELD = 'email'
#     username = models.CharField(max_length=30)
#     email = models.EmailField(unique=True)
#     is_active = models.BooleanField(default=False)
#     is_staff = models.BooleanField(default=False)

#     def get_full_name(self):
#         return self.email
#     def get_short_name(self):
#         return self.email

# class Member(models.Model):
# 	user = models.OneToOneField(User)
	
	# first_name = models.CharField(max_length = 30)
	# last_name = models.CharField(max_length = 30)
	# username = models.CharField(max_length = 30)
	# password = models.CharField(max_length = 30)
	# favorites = models.CharField(max_length = 200)
	# email = models.EmailField(max_length = 30)
	# is_active = models.BooleanField(default = True)

# class Quiz(models.Model):
# 	results = models.CharField(max_length = 300)
# 	date_taken = models.DateTimeField(default = timezone.now)
# 	user_id = models.OneToOneField(Member)

# class UserProfile(models.Model):
#     user = models.OneToOneField(User)
#     website = models.URLField(blank = True)

final_project/animal_adoption/animal_adoption/forms.py
from django import forms
from django.forms import Textarea
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *

class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('username', 'password', 'email',)

class CheckPassword(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('username', 'password')

# class RegistrationForm(forms.Form):
#     username = forms.EmailField(max_length=30)
#     password1 = forms.CharField()
#     password2 = forms.CharField()
#     email = forms.EmailField(max_length=100)

#     def clean(self):
#         cleaned_data = super(RegistrationForm, self).clean()
#         username = cleaned_data.get("username")
#         password1 = cleaned_data.get("password1")
#         password2 = cleaned_data.get("password2")

#     class Meta:
#         model = User

# class CreatePost(forms.ModelForm):
# 	class Meta:
# 		model = Member
# 		fields = [
# 			"username",
# 			"password",
# 		]

# class UpdatePost(forms.ModelForm):
# 	class Meta:
# 		user_post = forms.CharField()

# class PostForm(forms.ModelForm):
#     class Meta:

#         fields = [
#             "title",
#             "content",
#         ]
#         widgets = {
#             "content": Textarea(attrs={"cols": 50, "rows": 10}),
        # }

final_project/animal_adoption/animal_adoption/views.py
import requests
import project.settings as settings
from datetime import date
from django.db import models
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, CreateView, DetailView
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseNotAllowed
from django import forms
from django.utils.datastructures import MultiValueDict
from .models import *
from .forms import *

class Home(View):

    template_name = "app/home.html"
    template = "app/home.html"

    def get(self, request, pk = None):
        return render(request, self.template)

    def post(self, request):
        return render(request, self.template)

class Login(View):

    template_name = "app/login.html"
    template = "app/login.html"

    def get(self, request):
        user_form = UserForm()
        profile_form = UserProfileForm()
        print(user_form)
        print(profile_form)
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }

        return render(request, self.template, context)

    def post(self,request):
        userName = request.POST['username']
        password = request.POST['password']

        list_of_users = UserProfile.objects.all()
        cur = False
        for each in list_of_users:
            if each.username == userName:
                cur = True
        if cur:
            current_user = UserProfile.objects.get(username = userName)
            print(userName)
            print(password)
            print(current_user.password)
     #       hash_password = make_password(password)
     #       print (hash_password)

            if (password == current_user.password):
                print(current_user.password)
                # request.session['member_id'] = current_user.id
                return redirect('animal_adoption:home')

            else:
                print('++++++++++++++++++++++')
                return HttpResponse('Incorrect password. Try again')
        else:
            print('++++++++++++++++++++++++')
            return HttpResponse('No account associated with username')

class Register(View):

    template_name = "app/login.html"
    template = "app/login.html"

    def get(self, request):
        if request.user.is_authenticated():
            return render(request, 'home.html', {})
        user_form = UserForm()
        profile_form = UserProfileForm()
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, self.template, context)

    def post(self, request):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        #print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
        print(user_form)
        print(profile_form)

        list_of_users = UserProfile.objects.all()
        cur1 = True
        cur2 = True
        for each in list_of_users:
            #print(each.username)
            if each.username == request.POST['username']:
                cur1 = False
            if each.email == request.POST['email']:
                cur2 = False

        if cur1 and cur2:
            if profile_form.is_valid():
                # user = user_form.save()
                profile = profile_form.save(commit = False)
                # profile.user = user_form.save()
                profile.save()
                # user.save()
                return redirect('/')

            else:
                context = {
                    'user_form': user_form,
                    'profile_form': profile_form
                }

                return render(request, self.template, context)
        else:
            if not cur1 and not cur2:
                return HttpResponse("Account already exists")
            elif not cur1 and cur2:
                return HttpResponse("Username already taken")
            elif cur1 and not cur2:
                return HttpResponse("Email already taken")


class Adopt(View):

    template_name = "app/adopt.html"
    template = "app/adopt.html"

    def get(self, request, pk = None):
        return render(request, self.template)

    def post(self, request):
        return render(request, self.template)

class APISample(View):

    template = "app/home.html"

    def get(self, request, pk= None):
        
        barnyardQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=barnyard"
        randomBarnyard = requests.get(barnyardQuery).json()
        barnyard = randomBarnyard['petfinder']['petIds']['id']['$t']

        birdQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=bird"
        randomBird = requests.get(birdQuery).json()
        bird = randomBird['petfinder']['petIds']['id']['$t']

        catQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=cat"
        randomCat = requests.get(catQuery).json()
        cat = randomCat['petfinder']['petIds']['id']['$t']

        dogQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=dog"
        randomDog = requests.get(dogQuery).json()
        dog = randomDog['petfinder']['petIds']['id']['$t']

        horseQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=horse"
        randomHorse = requests.get(horseQuery).json()
        horse = randomHorse['petfinder']['petIds']['id']['$t']

        pigQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=pig"
        randomPig = requests.get(pigQuery).json()
        pig = randomPig['petfinder']['petIds']['id']['$t']

        reptileQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=reptile"
        randomReptile = requests.get(reptileQuery).json()
        reptile = randomReptile['petfinder']['petIds']['id']['$t']

        smallfurryQuery = "http://api.petfinder.com/pet.getRandom?key=" + settings.SECRET_KEY + "&format=json"+"&animal=smallfurry"
        randomSmallfurry = requests.get(smallfurryQuery).json()
        smallfurry = randomSmallfurry['petfinder']['petIds']['id']['$t']

        petList = []
        idList = [barnyard,bird,cat,dog,horse,pig,reptile,smallfurry]

        for ID in idList:
            petQuery = "http://api.petfinder.com/pet.get?key=" + settings.SECRET_KEY + "&id=" + ID + "&format=json"
            randomPet = requests.get(petQuery).json()
            petList.append(randomPet['petfinder']['pet'])

        name,animal,age,sex,size,breed,shelterName,location,ID,photos = [],[],[],[],[],[],[],[],[],[]

        for i in range(len(petList)):
            name.append(petList[i]['name']['$t'])
            animal.append(petList[i]['animal']['$t'])
            age.append(petList[i]['age']['$t'])
            ID.append(petList[i]['id']['$t'])

            if 'photos' in petList[i]['media'].keys():
                for each in petList[i]['media']['photos']['photo']:
                    #print(each.keys())
                    if each['@size'] == 'pn':
                        photos.append(each['$t'])
                        break
                try:
                    photos[i]
                except IndexError:
                    for each in petList[i]['media']['photos']['photo']:
                        if each['@size'] == 'x':
                            photos.append(each['$t'])
                            break

                try:
                    photos[i]
                except IndexError:
                    photos.append('http://www.jackspets.com/Images/Pet-Care-Information/Pet-Care-Information.png')
                #print(photos[i])
                # print("")
                # print("")

            else:
                photos.append("http://reddeerspca.com/images/content/nophoto.jpg")
            #print(photos[i])
            #print("")
            #print('')

            if petList[i]['sex']['$t'] == 'M':
                sex.append('Male')
            elif petList[i]['sex']['$t'] == 'F':
                sex.append('Female')
            else:
                sex.append('Unknown')

            if petList[i]['size']['$t'] == 'S':
                size.append('Small')
            elif petList[i]['size']['$t'] == 'M':
                size.append('Medium')
            elif petList[i]['size']['$t'] == 'L':
                size.append('Large')
            elif petList[i]['size']['$t'] == 'XL':
                size.append('Extra-Large')


            if type(petList[i]['breeds']['breed']) == type(petList):
                bred = []
                for each in petList[i]['breeds']['breed']:
                    bred.append(each['$t'])
                breed.append(bred)

            elif type(petList[i]['breeds']['breed']) == type(randomPet):
                breed.append([petList[i]['breeds']['breed']['$t']])

            location.append([petList[i]['contact']['city']['$t'],petList[i]['contact']['state']['$t']])

        searchFiltered= {}
        searchFiltered['petfinder'] = {}
        for i in range(len(petList)):
            #print(sex)
            searchFiltered['petfinder'][name[i]] = {}
            searchFiltered['petfinder'][name[i]]['info'] = [name[i],
            photos[i],
            " Animal: "+animal[i],
            " Age: "+ age[i],
            " Sex: "+ sex[i],
            " Size: "+ size[i],
            " Breed: "+"/".join(breed[i]),

final_project/animal_adoption/animal_adoption/templates/app/adopt.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Home</title>

	
	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
	<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
	<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

</head>

<body>
{% extends 'app/base.html' %}
{% block content %}
<script type="text/javascript" src="js/materialize.min.js"></script>
{% endblock %}
</body>

</html>

final_project/animal_adoption/animal_adoption/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	
	{% load staticfiles %}

	<meta charset="UTF-8">
	<title>Base</title>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'> -->
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Droid+Sans+Mono|Glegoo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito|Poiret+One" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'animal_adoption/base_style.css' %}">
</head>
<body>

    <header>
        <div class = 'title-header'><h1 class = "title">PetSearcher</h1></div>
        <div class="page-header">
    	        <h1><a href="/" id = "home">HOME</a></h1>
                <!-- <h1><a href="adopt/" id = "adopt"> ADOPT</a></h1> -->
                <!-- <h1><a href="care/" id = "care">CARE</a></h1> -->
                <h1><a href="login/" id = "login">LOGIN</a></h1>
        </div>
    </header>
    
   

    {% block content %}
    {% endblock %}
      
</body>
</html>

final_project/animal_adoption/animal_adoption/templates/app/home.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Home</title>


	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
	<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

</head>

<body>
{% extends 'app/base.html' %}
{% block content %}

	<!-- {{ petfinder }} -->

	<div class = "search-div">
		<article class = "search">
	    	<!-- <p>Search function here</p> -->

	    	<form action = "{% url 'animal_adoption:find_pet' %}" method = "POST">
			{% csrf_token %}
			<div class = "search-options">
				<h1>Location</h1>
				<input name = "location" type = "text" placeholder="Search by ZIP code or city">
			</div>

			<div class = "search-options">
			<h1>Animal</h1>
			<select name = "animal">
			  <option value="">Any</option>
			  <option value="barnyard">Barnyard</option>
			  <option value="bird">Bird</option>
			  <option value="cat">Cat</option>
			  <option value="dog">Dog</option>
			  <option value="horse">Horse</option>
			  <option value="pig">Pig</option>
			  <option value="reptile">Reptile</option>
			  <option value="smallfurry">Small Mammal</option>
			</select>
			</div>
			
			<div class = "search-options">
			<h1>Breed</h1>
			<input name = "breed" type = "text" placeholder="Enter a breed">
			</div>

			<div class = "search-options">
			<h1>Sex</h1>
			<select name = "sex">
			  <option value="">Any</option>
			  <option value="M">Male</option>
			  <option value="F">Female</option>
			</select>
			</div>

			<div class = "search-options">
			<h1>Size</h1>
				<select name = "size">
				  <option value="">Any</option>
				  <option value="S">Small</option>
				  <option value="M">Medium</option>
				  <option value="L">Large</option>
				  <option value="XL">Extra-Large</option>
				</select>
			</div>
			
			<div class = "search-options">
			<h1>Age</h1>
				<select name = "age">
				  <option value="">Any</option>
				  <option value="Baby">Baby</option>
				  <option value="Young">Young</option>
				  <option value="Adult">Adult</option>
				  <option value="Senior">Senior</option>
				</select>
			</div>

			<input type="submit" value = "Search" class = "search-button">
			</form>

	    </article>

	</div>

	<aside class = "aside-1">
    	<!-- <p>Shelter search function here</p> -->
		<article class = "shelter-search">

	    	<form action = "{% url 'animal_adoption:find_shelter' %}" method = "POST">
				{% csrf_token %}
				<br>
				<!-- <br> -->
				<div class = "shelter-search-text">
					<h1>Location</h1>
					<input type = 'text' name = 'location' placeholder="Search by ZIP code or city">
				</div>
				<div class = "shelter-search-text">
					<h1>Name</h1>
					<input type = 'text' name = 'name' placeholder="Name of the shelter">
					<br>
					<!-- <br> -->
					<input type = 'submit' value = 'Search' class = "shelter-search-button">
				</div>
			</form>

		</article>
    </aside>

    

	<!-- <div class = "featured-div">

			<article class = "featured-pets">
				
				<p>Featured pets here</p>
		        
			</article> -->


		           <!--  <SCRIPT src="https://fpm.petfinder.com/js/fpmstyle.js"></SCRIPT>
            <SCRIPT src="https://fpm.petfinder.com/fp/petfeed.cgi?lang=json&callback=fpm1&state=&shelter=&animal=&age=&ref=123123412asdgfasdfg234qlgkhj1p928y4"></SCRIPT> -->

    <!-- </div> -->

    <div class = "featured-div">
		<!-- <h2>Featured Pets</h2> -->
		{% for value in petfinderValues %}

			<div class = "featured-pets">
				{% for info in value.info %}
					{% if "http" in info %}
						<img id="featured-pet-photo" src={{info}} alt="Thumbnail Picture">
					{% else %}
						<div class = "featured-pet-info">{{info}}</div>
					{% endif %}

				{% endfor %}
				<form action = "{% url 'animal_adoption:details' %}?ID={{value.ID}}" method = "POST">
						{% csrf_token %}
						<input type = "submit" value = "Details" class = "button1">
					</form>

				<br>
				<br>
			</div>
		{% endfor %}
	</div>

		

    	</article>

    <aside class = "aside-2">
    	
		<article class = "share">

	   		<!-- <p>Share this page</p> -->
				<a href="https://www.facebook.com/sharer/sharer.php?u=wikipedia.org" target="_blank">
					<img class = "share-photo" id="facebook-photo" src="https://scontent-yyz1-1.xx.fbcdn.net/t31.0-8/11930988_10154088276211729_2432197377106462187_o.png" alt="facebook">
				</a>

				<a href="https://twitter.com/home?status=Check%20out%20http%3A//wikipedia.org!" target="_blank">
					<img class = "share-photo" id="twitter-photo" src="http://www.sketchappsources.com/resources/source-image/twitterlogo_1x.png" alt="twitter">
				</a>

				<a href="mailto:?subject=Check%20out%20PetSearcher!&body=http://wikipedia.org" target="_blank">
					<img class = "share-photo" id="mail-photo" src="http://aqbsoft.com/m/photos/get_image/file/b491e1e7f273f5a2c9c3307ca69ff8f3.jpg" alt="email">
				</a>
		</article>
    </aside>


    

    <!-- <aside class = "aside-2">
		<p>Help</p>
    </aside>

    <aside class = "share">
		<p>Share this page</p>
    </aside> -->


{% endblock %}
</body>

</html>

final_project/animal_adoption/animal_adoption/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Index</title>

    {% load staticfiles %}

    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="static/animal_adoption/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.0/foundation.min.js"></script> -->
    <script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    

</head>
<body>
  {% if form.errors %}
        <p class="errors">Please correct the errors below: {{ form.non_field_errors }}</p>
    {% endif %}

    <h3>Create an Account</h3>

    <form method="POST" action="{% url 'animal_adoption:home' %}" class="wide">
    {% csrf_token %}
        <p>
          <label for="id_username">Username: </label>
          <br>
          <input type = "text">
          {% if form.username.errors %}
            <p class="errors">{{ form.username.errors.as_text }}</p>
          {% endif %}
          {{ form.username }}
        </p>
        <p>
          <label for="id_email">Email: </label>
          <br>
          <input type = "text">
          {% if form.email.errors %}
            <p class="errors">{{ form.email.errors.as_text }}</p>
          {% endif %}
          {{ form.email }}
        </p>
        <p>
          <label for="id_password1">Password: </label>
          <br>
          <input type = "password">
          {% if form.password1.errors %}
            <p class="errors">{{ form.password1.errors.as_text }}</p>
          {% endif %}
          {{ form.password1 }}
        </p>
        <p>
          <label for="id_password2">Confirm Password: </label>
          <br>
          <input type = "password">
          {% if form.password2.errors %}
            <p class="errors">{{ form.password2.errors.as_text }}</p>
          {% endif %}
          {{ form.password2 }}
        </p>
        <p class="submit"><input type="submit" value="Register" class = "button"></p>
    </form>

    {% if form_auth.errors %}
        <p class="error">Please correct the errors below:</p>
    {% endif %}


    <h3>Log in</h3>

    <form method="POST" action="{% url 'animal_adoption:login' %}">
        {% csrf_token %}
        
        <input type="text" placeholder="Username" name="username"/>
        <input type="text" placeholder="Password" name="password"/>
        <input type="submit" value = "Log In" class = "button">
    <!--     <dl>
            <dt>
                <label for="id_username">Username:</label>
                <br>
                <input type = "text">
                {% if form.username.errors %} 
                    <span class="error">{{ form.username.errors|join:", " }}</span>
                {% endif %}
            </dt>

            <dd>{{ form_auth.username }}</dd>

            <dt>
                <label for="id_password">Password:</label>
                <br>
                <input type = "password">
                {% if form.password.errors %}
                    <span class="error">{{ form.password.errors|join:", " }}</span>
                {% endif %}
            </dt>

            <dd>{{ form_auth.password }}</dd>

            <dt><input type="submit" value="Log in" class = "button"/></dt>

        </dl> -->
    </form>
</body>
</html>

final_project/animal_adoption/animal_adoption/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login or Register</title>

    {% load staticfiles %}

    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito|Poiret+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa|Droid+Sans+Mono|Glegoo" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'animal_adoption/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'animal_adoption/login_style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script   src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    

</head>
<body>

    <div class = "account">
        <div id = "register">
        	<h3>Create an Account</h3>

        	<form action="{% url 'animal_adoption:register' %}" method = "POST">
        		{% csrf_token %}
            {{ profile_form.as_p }}
        		
        		<input type = "submit" class = "button" value = "Register"/>
        	</form>
        </div>

        <div id = "login">

        <h3>Log in</h3>

            <form method="POST" action="{% url 'animal_adoption:login' %}">
                {% csrf_token %}
                
                <input type="text" placeholder="Username" name="username"/>
                <br>
                <input type="password" placeholder="Password" name="password"/>
                <br>
                <input type="submit" value = "Log In" class = "button">
            </form>
        </div>
    </div>
</body>
</html>

final_project/animal_adoption/animal_adoption/templates/app/search.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Find Pet</title>
</head>
<body>
	{% extends 'app/base.html' %}
	{% block content %}

		{% for value in petfinderValues %}

			<div id = "search-info">
				{% for info in value.info %}
					{% if "http" in info %}
						<img class = "pet-photo" src={{info}} alt="Thumbnail Picture">
					{% else %}
						<div class = "pet-info">{{info}}</div>
					{% endif %}

					<!-- <br> -->

				{% endfor %}
				<form action = "{% url 'animal_adoption:details' %}?ID={{value.ID}}" method = "POST">
						{% csrf_token %}
						<input type = "submit" value = "Details" class = "button1">
				</form>

				<br>
				<br>
			</div>

		{% endfor %}



	{% endblock %}
</body>
</html>